### ISSUE TITLE
Incompatibility with FireGento_FastSimpleImport2

### ISSUE THREAD

**Issue by EliasKotlyar** [firebearstudio/importexportfree#1]
Hello,

We encountered a Bug with the combination of this Plugin with the FireGento_FastSimpleImport2 Plugin. 

You can find the exact Information here:
https://github.com/firegento/FireGento_FastSimpleImport2/issues/2

The issue appears as soon you try to import with the demo command:
bin/magento fastsimpleimport2demo:products:importsimple

Here is a Exception Log:
[2016-03-30 06:40:50] main.CRITICAL: exception 'ReflectionException' with message 'Class Magento\Framework\Model\Entity\MetadataPool does not exist' in /home/prashantr/public_html/ves_yume_magento/vendor/magento/framework/Code/Reader/ClassReader.php:29
Stack trace:
#0 /home/prashantr/public_html/ves_yume_magento/vendor/magento/framework/Code/Reader/ClassReader.php(29): ReflectionParameter->getClass()
#1 /home/prashantr/public_html/ves_yume_magento/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Firebear\Import...')
#2 /home/prashantr/public_html/ves_yume_magento/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Firebear\Import...')
#3 /home/prashantr/public_html/ves_yume_magento/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Firebear\Import...', Array)
#4 /home/prashantr/public_html/ves_yume_magento/vendor/magento/module-import-export/Model/Import/Entity/Factory.php(42): Magento\Framework\ObjectManager\ObjectManager->create('Magento\Catalog...')
#5 /home/prashantr/public_html/ves_yume_magento/vendor/magento/module-import-export/Model/Import.php(224): Magento\ImportExport\Model\Import\Entity\Factory->create('Magento\Catalog...')
#6 /home/prashantr/public_html/ves_yume_magento/vendor/magento/module-import-export/Model/Import.php(571): Magento\ImportExport\Model\Import->_getEntityAdapter()
#7 /home/prashantr/public_html/ves_yume_magento/var/generation/Firebear/ImportExport/Plugin/Model/Import/Interceptor.php(154): Magento\ImportExport\Model\Import->validateSource(Object(FireGento\FastSimpleImport2\Model\ArrayAdapter))
#8 /home/prashantr/public_html/ves_yume_magento/app/code/FireGento/FastSimpleImport2/Model/Importer.php(74): Firebear\ImportExport\Plugin\Model\Import\Interceptor->validateSource(Object(FireGento\FastSimpleImport2\Model\ArrayAdapter))
#9 /home/prashantr/public_html/ves_yume_magento/app/code/FireGento/FastSimpleImport2/Model/Importer.php(66): FireGento\FastSimpleImport2\Model\Importer->_validateData(Array)
#10 /home/prashantr/public_html/ves_yume_magento/app/code/FireGento/FastSimpleImport2Demo/Console/Command/AbstractImportCommand.php(106): FireGento\FastSimpleImport2\Model\Importer->processImport(Array)
#11 /home/prashantr/public_html/ves_yume_magento/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): FireGento\FastSimpleImport2Demo\Console\Command\AbstractImportCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/prashantr/public_html/ves_yume_magento/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/prashantr/public_html/ves_yume_magento/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(FireGento\FastSimpleImport2Demo\Console\Command\Product\ImportSimple), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/prashantr/public_html/ves_yume_magento/vendor/magento/framework/Console/Cli.php(49): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/prashantr/public_html/ves_yume_magento/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /home/prashantr/public_html/ves_yume_magento/bin/magento(25): Symfony\Component\Console\Application->run()
#17 {main}

Greetings
Elias

**Comment by biotech** [comment]
@graffov87 we have to check if our extension can works together with https://github.com/firegento/FireGento_FastSimpleImport2/ enabled, this is can be the case that both used for various export / import processes

**Comment by biotech** [comment]
We do not consider this as possible case now use our extension with FireGento_FastSimpleImport2, extensions is quite similar by idea but have totally different implementation
