### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Gamewalker** [firebearstudio/importexportfree#14]
Hello,

I followed the steps at 
https://firebearstudio.com/blog/improved-import-magento-2-extension-manual.html

and I get the following error:
`[Sun Apr 30 04:56:11.447444 2017] [fcgid:warn] [pid 6727] [client 2a02:908:680:1be0:c45e:d7bc:a4c7:7c35:61266] mod_fcgid: stderr: PHP Fatal error:  Cannot use Magento\\Framework\\Module\\Dir\\Reader as Reader because the name is already in use in /var/www/dc/html/app/code/Firebear/ImportExport/Model/Source/Config/SchemaLocator.php on line 10,

**Comment by biotech** [comment]
Fixed with last release
