### ISSUE TITLE
Override of the import validation

### ISSUE THREAD

**Issue by dmanners** [firebearstudio/importexportfree#16]
We have a system currently using the import export module. When the csv validation has issues not from the FireBear validation but from the standard Magento import validation process these will get overridden.

In the `Firebear\ImportExport\Model\Job\Processor::process` method when it catches an exception it will load the history and set the summary. But the Magento validation has already added the appropriate log messages to the history for this process. The end result is that when you get `<b>Data validation is failed. Please fix errors and re-upload the file..</b>` in the summary and not the "real" error message as provided by the Magento core import validation.

**Comment by biotech** [comment]
Hi David! Thanks for you notice, we will for sure fix that. We are working now on complete refactoring and improved achitecture of paid version, will be released soon and available for downloads for all customers

**Comment by dmanners** [comment]
Thank you for the information @biotech
