### ISSUE TITLE
app/code/Firebear/ImportExport/Model/Source/Config/SchemaLocator.php on line 10

### ISSUE THREAD

**Issue by idedooij** [firebearstudio/importexportfree#19]
Sorry to raise this issue again (I have seen it under the closed issues).
I downloaded the lastest version, but I still get this error when I go to import section in my Magento admin.

thanks,
iwan

**Comment by franktjinaton** [comment]
Same here. Pls check

**Comment by graffov87** [comment]
The module fixed. Please, upgrade module via Composer and check.
