### ISSUE TITLE
I have the problem with import 

### ISSUE THREAD

**Issue by biletskyidm** [firebearstudio/importexportfree#2]
I've instaled trial version and when I'm trying to import csv file(your sample) I get the error http://screencast.com/t/fjKnt5F0lYUY
How can I see more details about error?

**Comment by nikolaevas** [comment]
Hello Dmitry,
Can you please send us your csv file and more details about import settings?

**Comment by biletskyidm** [comment]
[catalog_product (1).txt](https://github.com/firebearstudio/importexport/files/219170/catalog_product.1.txt)

**Comment by reyazmoosa** [comment]
Dear Team,

I am getting the same error mentioned by @BiletskiyDmitriy  
Any idea how to fix it?

FYI @nikolaevas 

Best regards
Reyaz

**Comment by nikolaevas** [comment]
Hello guys,

Sorry for delay. The problem should be fixed now.

**Comment by reyazmoosa** [comment]
Thanks a lot @nikolaevas
