### ISSUE TITLE
error in compiling

### ISSUE THREAD

**Issue by idedooij** [firebearstudio/importexportfree#21]
Hi,

The module gives me the error below, when I try to compile it:

Fatal error:  Cannot use Magento\Framework\Module\Dir\Reader as Reader because the name is already in use in /xxxxxxxxxxxxxxx/public_html/vendor/firebear/importexportfree/Model/Source/Config/SchemaLocator.php on line 10

Fatal error: Cannot use Magento\Framework\Module\Dir\Reader as Reader because the name is already in use in /xxxxxxxxxxxxxxxx/public_html/vendor/firebear/importexportfree/Model/Source/Config/SchemaLocator.php on line 10

Any ideas?

thanks

**Comment by biotech** [comment]
We will investigate and get back to you soon!

**Comment by biotech** [comment]
@idedooij would be possible for you to provide more details? is that error now occur when you compile with a disabled extension? thank you!
