### ISSUE TITLE
Issue when running compose command

### ISSUE THREAD

**Issue by ebofi** [firebearstudio/importexportfree#23]
Hi, 
I just run the initial composer command to start the install process.

But im getting an Composer error on my ssh

Fatal error: Call to undefined function Symfony\Polyfill\Mbstring\iconv() in pha                                                             r:///opt/cpanel/composer/bin/composer/vendor/symfony/polyfill-mbstring/Mbstring.                                                             php on line 513

**Comment by biotech** [comment]
This is not related to our extension https://github.com/symfony/polyfill/issues/45
