### ISSUE TITLE
import hang

### ISSUE THREAD

**Issue by to8gal** [firebearstudio/importexportfree#5]
Hello, after enabling your module on my dev magento2 when I try to import the please wait hang forever,

I´m using the free version, all work fine when I disable the module

**Comment by sennin32** [comment]
Got same problem.
Work fine with clean installation.
Both 2.1.0 and 2.1.1 not work.
Any report from a paid version?

**Comment by biotech** [comment]
Hello guys! Please try current recent version of extension - should works great on recent M2 CE and EE versions!
