### ISSUE TITLE
SFTP DOES NOT SUPPORT. PLEASE SEE CODE BELOW TO MAKE SFTP TO WORK

### ISSUE THREAD

**Issue by nagrgk** [firebearstudio/importexportfree#7]
**step1 :** add new file to following location:  Firebear\ImportExport\Model\Filesystem\Io => Sftp.php
<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace Firebear\ImportExport\Model\Filesystem\Io;

/**
 * Extended FTP client
 */
class Sftp extends \Magento\Framework\Filesystem\Io\Sftp
{
    /**
     * Returns the last modified time of the given file
     * Note: Not all servers support this feature! Does not work with directories.
     *
     * @see http://php.net/manual/en/function.ftp-mdtm.php
     *
     * @param $filename
     * @return int
     */
    public function mdtm($filename)
    {
        return @ftp_mdtm($this->_conn, $filename);
    }
}

**step2 :** 
add test case to Firebear\ImportExport\Test\Unit\Model\Source\Type => SftpTest.php
<?php
namespace Firebear\ImportExport\Test\Unit\Model\Source\Type;

use Magento\Framework\TestFramework\Unit\Helper\ObjectManager as ObjectManagerHelper;
use Magento\ImportExport\Model\Import\ErrorProcessing\ProcessingErrorAggregatorInterface;
use Magento\Framework\App\Filesystem\DirectoryList;

class SftpTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ObjectManagerHelper
     */
    protected $objectManagerHelper;

    protected $_sftpClient;
    protected $_sftpMock;

    protected $varDirectory;
    protected $filesystem;
    protected $factory;
    protected $scopeConfigInterface;

    protected function setUp()
    {
        parent::setUp();

        $this->objectManagerHelper = new ObjectManagerHelper($this);

        $this->_sftpClient = $this->getMockBuilder('Firebear\ImportExport\Model\Filesystem\Io\Sftp')
            ->setMethods(
                [
                    'read'
                ]
            )
            ->getMock();
        $this->_sftpClient->expects($this->any())
            ->method('read')
            ->willReturn(true);
        
        $this->varDirectory = $this->getMock(
            'Magento\Framework\Filesystem\Directory\Write',
            ['getAbsolutePath'],
            [],
            '',
            false
        );
        //$this->varDirectory->expects($this->any())->method('getAbsolutePath')->will($this->returnValue(true));

        $this->filesystem = $this->getMock(
            'Magento\Framework\Filesystem',
            ['getDirectoryWrite'],
            [],
            '',
            false
        );
        $this->filesystem->expects($this->any())->method('getDirectoryWrite')->willReturn($this->varDirectory);
        $this->factory = $this->getMock('Magento\Framework\Filesystem\File\ReadFactory', [], [], '', false);
        $this->scopeConfigInterface = $this->getMock('Magento\Framework\App\Config\ScopeConfigInterface');

        $this->_sftpMock = $this->objectManagerHelper->getObject(
            'Firebear\ImportExport\Model\Source\Type\Sftp',
            [
                'scopeConfig' => $this->scopeConfigInterface,
                'filesystem' => $this->filesystem,
                'readFactory' => $this->factory
            ]
        );

        $this->_sftpMock->setClient($this->_sftpClient);

//        $this->_ftpMock = $this->getMockBuilder('Firebear\ImportExport\Model\Source\Type\Ftp')
//            ->setConstructorArgs(
//                [
//                    $this->getMockBuilder('Magento\Framework\App\Config\ScopeConfigInterface')
//                        ->disableOriginalConstructor()
//                        ->getMock(),
//                    $this->getMockBuilder('Magento\Framework\Filesystem')
//                        ->disableOriginalConstructor()
//                        ->getMock(),
//                    $this->getMockBuilder('Magento\Framework\Filesystem\File\ReadFactory')
//                        ->disableOriginalConstructor()
//                        ->getMock(),
//                ]
//            )
//            ->setMethods(
//                [
//                    'uploadSource',
//                    '_getSourceClient',
//                ]
//            )
//            ->getMock();
//
//        $this->_ftpMock->expects($this->any())
//            ->method('_getSourceClient')
//            ->willReturn($this->_ftpClient);

        $this->_sftpMock->setData('import_source', 'sftp');
        $this->_sftpMock->setData('sftp_file_path', '/public_html/import/products_2_replace.csv');
    }

    public function testUploadSource()
    {
        try {
            $result = $this->_sftpMock->uploadSource();
        } catch (\Exception $e) {
            $result = $e->getMessage();
        }
        $this->assertEquals('/var/www/local-mage2dev.com/magento2/var/import/sftp/products_2_replace.csv', $result);
    }
}

**step3:** add sftp source to Firebear\ImportExport\Model\Source\Type => Sftp.php
<?php
/**
 * @copyright: Copyright © 2015 Firebear Studio. All rights reserved.
 * @author: Firebear Studio <fbeardev@gmail.com>
 */

namespace Firebear\ImportExport\Model\Source\Type;

class Sftp extends AbstractType
{
    /**
     * @var string
     */
    protected $_code = 'sftp';

    /**
     * Download remote source file to temporary directory
     *
     * @return string
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function uploadSource()
    {
        if($client = $this->_getSourceClient()) {
            $sourceFilePath = $this->getData($this->_code . '_file_path');
            $fileName = basename($sourceFilePath);
            //return get_class($this->_directory);
            $filePath = $this->_directory->getAbsolutePath($this->getImportPath() . '/' . $fileName);
            $filesystem = new \Magento\Framework\Filesystem\Io\File();
            $filesystem->setAllowCreateFolders(true);
            $filesystem->checkAndCreateFolder($this->_directory->getAbsolutePath($this->getImportPath()));

            $result = $client->read($sourceFilePath, $filePath);

            if($result) {
                return $this->_directory->getAbsolutePath($this->getImportPath() . '/' . $fileName);
            } else {
                throw new \Magento\Framework\Exception\LocalizedException(__("File not found"));
            }
        } else {
            throw new  \Magento\Framework\Exception\LocalizedException(__("Can't initialize %s client", $this->_code));
        }
    }

    /**
     * Download remote images to temporary media directory
     *
     * @param $importImage
     * @param $imageSting
     *
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function importImage($importImage, $imageSting)
    {
        if($client = $this->_getSourceClient()) {
            $sourceFilePath = $this->getData($this->_code . '_file_path');
            $sourceDirName = dirname($sourceFilePath);
            $filePath = $this->_directory->getAbsolutePath($this->getMediaImportPath() . $imageSting);
            $dirname = dirname($filePath);
            if (!is_dir($dirname)) {
                mkdir($dirname, 0775, true);
            }
            if($filePath) {
                $result = $client->read($sourceDirName . '/' . $importImage, $filePath);
            }
        }
    }

    /**
     * Check if remote file was modified since the last import
     *
     * @param int $timestamp
     * @return bool|int
     */
    public function checkModified($timestamp)
    {
        if($client = $this->_getSourceClient()) {
            $sourceFilePath = $this->getData($this->_code . '_file_path');

            if(!$this->_metadata) {
                $this->_metadata['modified'] = $client->mdtm($sourceFilePath);
            }

            $modified = $this->_metadata['modified'];

            return ($timestamp != $this->_metadata['modified']) ? $modified : false;
        }

        return false;
    }

    /**
     * Prepare and return SFTP client
     *
     * @return \Firebear\ImportExport\Model\Filesystem\Io\Sftp
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    protected function _getSourceClient()
    {
        if(!$this->getClient()) {
            if($this->getData('host') && $this->getData('port') && $this->getData('user') && $this->getData('password')) {
                $settings = $this->getData();
            } else {
                $settings = $this->_scopeConfig->getValue(
                    'firebear_importexport/sftp',
                    \Magento\Store\Model\ScopeInterface::SCOPE_STORE
                );
            }

            $settings['passive'] = true;
            try {
                $connection = new \Firebear\ImportExport\Model\Filesystem\Io\Sftp();
                $connection->open(
                    $settings
                );
                $this->_client = $connection;
            } catch(\Exception $e){
                throw new  \Magento\Framework\Exception\LocalizedException(__($e->getMessage()));
            }

        }

        return $this->getClient();
    }
}

**step 4:** add source types to /Firebear/ImportExport/etc/ => source_types.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="source_types.xsd">
    <type name="dropbox" label="Dropbox" modelInstance="Firebear\ImportExport\Model\Source\Type\Dropbox" sortOrder="10">
        <field name="file_path" id="file_path" label="File Path" type="text" required="true" />
        <field name="access_token" id="access_token" label="Access Token" type="text" required="true" />
        
    </type>
    <type name="ftp" label="Ftp" modelInstance="Firebear\ImportExport\Model\Source\Type\Ftp" sortOrder="20">
        <field name="file_path" id="file_path" label="File Path" type="text" required="true" />
        <field name="host" id="host" label="Host" type="text" required="true" />
        <field name="port" id="port" label="Port" type="text" required="true" />
        <field name="user" id="username" label="Username" type="text" required="true" />
        <field name="password" id="password" label="Password" type="text" required="true" />
    </type>
	<type name="sftp" label="Sftp" modelInstance="Firebear\ImportExport\Model\Source\Type\Sftp" sortOrder="40">
        <field name="file_path" id="file_path" label="File Path" type="text" required="true" />
        <field name="host" id="host" label="Host" type="text" required="true" />
        <field name="port" id="port" label="Port" type="text" required="true" />
        <field name="user" id="username" label="Username" type="text" required="true" />
        <field name="password" id="password" label="Password" type="text" required="true" />
    </type>
    <type name="url" label="Url" modelInstance="Firebear\ImportExport\Model\Source\Type\Url" sortOrder="30">
        <field name="file_path" id="file_path" label="Url" type="text" required="true" />
    </type>
</config>

**step5 :** change config.xml :
<sftp>
                <port>22</port>
            </sftp>

**step6:** add sftp config settings: user should be username, not 'user'
<group id="sftp" translate="label" type="text" sortOrder="30" showInDefault="1" showInWebsite="1" showInStore="1">
                <label>SFTP</label>
                <field id="host" translate="label" type="text" sortOrder="10" showInDefault="1" showInWebsite="0" showInStore="0">
                    <label>Host</label>
                </field>
                <field id="port" translate="label" type="text" sortOrder="20" showInDefault="1" showInWebsite="0" showInStore="0">
                    <label>Port</label>
                </field>
                <field id="username" translate="label" type="text" sortOrder="30" showInDefault="1" showInWebsite="0" showInStore="0">
                    <label>Username</label>
                </field>
                <field id="password" translate="label comment" type="password" sortOrder="40" showInDefault="1" showInWebsite="0" showInStore="0">
                    <label>Password</label>
                    <comment>You will be able to define file path during import/export process</comment>
                </field>
            </group>

this makes sftp available and product import works with sftp.

FIREBEAR:No one using ftp now days and not secure. Please start adding some secure points to module if you build and sell it. We bought it and finally added our own code to work.

[Uploading sftp.zip…]()

**Comment by biotech** [comment]
Thanks for that piece - we will have look and implement full support of SFTP!

**Comment by biotech** [comment]
SFTP support added on full version - https://firebearstudio.com/improved-import.html
