### ISSUE TITLE
Import product having integrity constraint error

### ISSUE THREAD

**Issue by nagrgk** [firebearstudio/importexportfree#8]
Hi,

Can you please let us know if you have any fix for error, attached.
normally product update never works on enterprise version.
![update_product_error](https://cloud.githubusercontent.com/assets/2674815/20380543/b28773e4-acdd-11e6-94ad-924500adc6c4.png)

thanks

**Comment by biotech** [comment]
Recent version of extension (both paid and free) should works correctly on last version of M2 CE and EE. Please try again and let us know if you still have issues

**Comment by lburgosDO** [comment]
Hello, 

I have tried 3 different versions 1.2.0, 1.3.0 and the free version on Magento 2 EE 2.1.2. I receive the same error every time I try to update/add attributes to products. If I disable the module, it works fine. 

General system exception happened
Additional data: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`cmc_sandbox_magento`.`catalog_product_entity`, CONSTRAINT `CAT_PRD_ENTT_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set` (`attribute_set_i), query was: INSERT INTO `catalog_product_entity` (`updated_at`,`entity_id`) VALUES (?, ?) ON DUPLICATE KEY UPDATE `updated_at` = VALUES(`updated_at`)

Can you verify this works for my version? I have spent countless hours trying to troubleshoot and fix it.

**Comment by biotech** [comment]
@lburgosDO have you contact our support service? can you please update your ticket and we will help you with debug and fix asap!

**Comment by biotech** [comment]
Fixed with last update
